import AuthProvider from "./(components)/AuthProvider";
import Footer from "./(components)/Footer";
import Nav from "./(components)/Nav";
import Navbar from "./(components)/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          {/* <Nav /> */}
          <Navbar/>
          <div>{children}</div>
          <Footer />
        </body>

      </AuthProvider>
    </html>
  );
}
