import AuthProvider from "./(components)/AuthProvider";
import Navbar from "./(components)/Navbar";
import "./globals.css";
import Footer from "./(components)/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
<<<<<<< HEAD
        <body className="bg-gray-100">
          <Nav />
          <div className="m-2">{children}</div>
=======
        <body>
          {/* <Nav /> */}
          <Navbar/>
          <div>{children}</div>
<<<<<<< HEAD
>>>>>>> main
          <Footer />
=======
          
>>>>>>> origin/main
        </body>

      </AuthProvider>
    </html>
  );
}
